spring.profiles.active: development
---
spring:
  profiles: cloud
  application:
    name: ${vcap.application.name}
cloud: 
  aws:
    s3:
      access-key-id: ${vcap.services.pcfawss3.credentials.access-key-id}
      access-key-secret: ${vcap.services.pcfawss3.credentials.secret_access_key}
      default-bucket: ${vcap.services.pcfawss3.credentials.bucket}
    region:
      static: ${vcap.services.pcfawss3.credentials.region}
    dynamodb:
      access-key-id: ${vcap.services.pcfawsddb.credentials.access-key-id}
      access-key-secret: ${vcap.services.pcfawsddb.credentials.secret_access_key}
      region: 
        static: ${vcap.services.pcfawsddb.credentials.region}
  
multipart: 
  maxFileSize: 5MB
  maxRequestSize: 5MB
management: 
  cloudfoundry: 
    skip-ssl-validation: true 
  endpoints: 
    web:
      exposure:
        include: "*"
---
spring:
  profiles: development
  application:
    name: pcfaws
cloud: 
  aws:
    s3:
      access-key-id: REPLACE
      access-key-secret: REPLACE
      default-bucket: REPLACE
    region: 
      static: us-east-2
    dynamodb:
      access-key-id: REPLACE
      access-key-secret: REPLACE
      region: 
        static: us-east-1
multipart: 
  maxFileSize: 5MB
  maxRequestSize: 5MB
management: 
  cloudfoundry: 
    skip-ssl-validation: true 
  endpoints: 
    web:
      exposure:
        include: "*"